#
# $Source: f:/miner/source/vga/rcs/makefile $
# $Revision: 1.7 $
# $Author: matt $
# $Date: 1996/03/05 13:35:39 $
#
# Makefile for bios functions
#

# What to install, and where to install it
INSTALL_TARGS = vga.h vga.lib

# What to clean
CLEAN_TARGS = $(OBJDIR)\*.obj

# What libs to make
LIBS = vga

# What object files for the lib
VGA_OBJS = vga.obj palette.obj vesa.obj modex.obj framebuf.obj

#rules and targets common to all Miner makefiles
!include ..\..\init\wmake.def

